CREATE TABLE product_foto (
  id_barang INT PRIMARY KEY,
  tipe VARCHAR(30) NOT NULL,
  data MEDIUMBLOB NOT NULL,
  diubah TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (id_barang) REFERENCES product(id_barang) ON DELETE CASCADE
);